### ISSUE TITLE
简单粗暴的做了个 Android 版本

### ISSUE THREAD

**Issue by li-yu** [lexrus/Huahui#3]
大神你好，由于不会 iOS 开发，编译不了。所以简单实现了个 Android 版本，还请指教以及交流学习 (*^__^*) 
[https://github.com/li-yu/Huahui-Android](https://github.com/li-yu/Huahui-Android)

**Comment by lexrus** [comment]
好赞。不过你这个 Words.java 怎么更新呢？

**Comment by li-yu** [comment]
@lexrus 初版先写死了，后面周末有时间会考虑从 Server 上拉单词列表更新。主要是看到你的 iOS 版本，才有了这个初版 ，嘿嘿

**Comment by lexrus** [comment]
我现在是在 Xcode Playground 里面更新这个，在考虑写个脚本做这个事。

**Comment by lexrus** [comment]
已在 README 里加上了你的仓库的链接。另外写了一个 makefile 方便你生成 Words.java:
https://github.com/lexrus/Huahui

**Comment by li-yu** [comment]
@lexrus 这几天抽空改了下，直接解析 HTML 拉取单词列表了，这样体验好多了，已更新。[https://github.com/li-yu/Huahui-Android](https://github.com/li-yu/Huahui-Android)
